### ISSUE TITLE
Crash in Compose beta04

### ISSUE THREAD

**Issue by gustavkarlsson** [rjrjr/compose-backstack#54]
```
java.lang.NoSuchFieldError: No static field Companion of type Landroidx/compose/foundation/layout/BoxScope$Companion; in class Landroidx/compose/foundation/layout/BoxScope; or its superclasses (declaration of 'androidx.compose.foundation.layout.BoxScope' appears in /data/app/~~AX-A0zaOMg9SMabil1N_6Q==/se.gustavkarlsson.skylight.android.develop-t5puiJgmSbi1p-8tA0NHWg==/base.apk)
        at com.zachklipp.compose.backstack.BackstackKt.Backstack(Backstack.kt:234)
        at com.zachklipp.compose.backstack.BackstackKt.Backstack(Backstack.kt:166)
```

I'm guessing it has to do with this change: https://android-review.googlesource.com/c/platform/frameworks/support/+/1619084

**Comment by zach-klippenstein** [comment]
Can't repro after upgrading to beta 05 in #55.
